# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRPA9zkubuVVI_Wq1C2v4eDdeS8LPHHB
"""

# # Part 2: Computer Vision Problem Formulation and CNN Prototype

# In this notebook, I am solving a computer vision problem using a simple CNN.
# The dataset contains manufacturing product surface images, and the goal is to
# classify each image into one of four classes:

# - normal
# - scratch
# - dent
# - stain

# This is a good example of how CNNs can learn visual patterns directly from images.

import os
import random
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical

# reproducibility
np.random.seed(42)
tf.random.set_seed(42)
random.seed(42)

# create folders for outputs
os.makedirs("results", exist_ok=True)
os.makedirs("sample_predictions", exist_ok=True)

sns.set_style("whitegrid")

print("TensorFlow version:", tf.__version__)

# ## Task 1: Problem Identification

# This dataset represents an **image classification** problem.

# I selected image classification because each image has one label only, and the goal
# is to predict the category of the full image. There are no bounding boxes, masks,
# or pixel-level annotations, so it is not object detection or segmentation.

labels_df = pd.read_csv("/content/labels.csv")
print("Dataset shape:", labels_df.shape)
labels_df.head()

# ## Task 2: Dataset Exploration

# I will now explore:
# - number of classes
# - number of images per class
# - sample images
# - image sizes
# - whether the dataset is balanced

print("Class names:")
print(labels_df["class"].unique())

print("\nImages per class:")
print(labels_df["class"].value_counts())

plt.figure(figsize=(7,4))
sns.countplot(data=labels_df, x="class", palette="Set2")
plt.title("Images per Class")
plt.xlabel("Class")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# show one sample image from each class
classes = sorted(labels_df["class"].unique())

fig, axes = plt.subplots(1, len(classes), figsize=(16,4))

for i, cls in enumerate(classes):
    sample_path = labels_df[labels_df["class"] == cls]["filename"].iloc[0]
    img = Image.open("/content/dent_001.png")
    axes[i].imshow(img)
    axes[i].set_title(cls)
    axes[i].axis("off")

plt.suptitle("Sample Images from Each Class", y=1.02)
plt.tight_layout()
plt.show()

# ### Short observation
# The dataset has 4 classes with 120 images in each class, so it is balanced.
# That makes training easier because there is no major class imbalance problem.
# The image sizes may vary, so resizing is needed before model training.

# ## Task 3: Image Preprocessing

# For preprocessing, I will:
# - resize images to a fixed size
# - normalize pixel values
# - split data into train, validation, and test sets
# - use light image augmentation

class_names = sorted(labels_df["class"].unique())
class_to_idx = {name: idx for idx, name in enumerate(class_names)}
idx_to_class = {idx: name for name, idx in class_to_idx.items()}

labels_df["label"] = labels_df["class"].map(class_to_idx)

print("Class mapping:")
print(class_to_idx)

train_df, temp_df = train_test_split(
    labels_df,
    test_size=0.30,
    stratify=labels_df["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

print("Train set:", train_df.shape)
print("Validation set:", val_df.shape)
print("Test set:", test_df.shape)

IMG_SIZE = (128, 128)

def load_images(dataframe, img_size=(128, 128)):
    images = []
    labels = []

    for _, row in dataframe.iterrows():
        img_path = row["filename"]
        label = row["label"]

        img = Image.open(img_path).convert("RGB")
        img = img.resize(img_size)
        img = np.array(img, dtype=np.float32) / 255.0

        images.append(img)
        labels.append(label)

    return np.array(images), np.array(labels)

X_train, y_train = load_images(train_df, IMG_SIZE)
X_val, y_val = load_images(val_df, IMG_SIZE)
X_test, y_test = load_images(test_df, IMG_SIZE)

print("Train image tensor:", X_train.shape)
print("Validation image tensor:", X_val.shape)
print("Test image tensor:", X_test.shape)

num_classes = len(class_names)

y_train_cat = to_categorical(y_train, num_classes=num_classes)
y_val_cat = to_categorical(y_val, num_classes=num_classes)
y_test_cat = to_categorical(y_test, num_classes=num_classes)

print("One-hot encoded label shape:", y_train_cat.shape)

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.08),
    layers.RandomZoom(0.10)
])

## Task 4: CNN Model Creation

I kept the CNN fairly simple because this is a prototype model.
It still includes all the core CNN components required in the assignment:
- convolution
- activation
- pooling
- flattening
- dense layer
- output layer

model = models.Sequential([
    data_augmentation,

    layers.Conv2D(32, (3, 3), activation="relu", input_shape=(128, 128, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(num_classes, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

## Task 5: Model Training and Evaluation

I will train the model and monitor validation performance.
Early stopping is used so that training stops if validation loss stops improving.

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train_cat,
    validation_data=(X_val, y_val_cat),
    epochs=20,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(history.history["accuracy"], label="Train Accuracy")
axes[0].plot(history.history["val_accuracy"], label="Validation Accuracy")
axes[0].set_title("Accuracy Curves")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Accuracy")
axes[0].legend()

axes[1].plot(history.history["loss"], label="Train Loss")
axes[1].plot(history.history["val_loss"], label="Validation Loss")
axes[1].set_title("Loss Curves")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")
axes[1].legend()

plt.tight_layout()
plt.savefig("results/accuracy_loss_curves.png", dpi=120, bbox_inches="tight")
plt.show()

test_loss, test_acc = model.evaluate(X_test, y_test_cat, verbose=0)

print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f}")

y_prob = model.predict(X_test, verbose=0)
y_pred = np.argmax(y_prob, axis=1)

print(classification_report(y_test, y_pred, target_names=class_names))

cm = confusion_matrix(y_test, y_pred)

fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap="Blues", ax=ax)
plt.title("Confusion Matrix")
plt.tight_layout()
plt.savefig("results/confusion_matrix.png", dpi=120, bbox_inches="tight")
plt.show()

# sample predictions
sample_count = 8
indices = np.random.choice(len(X_test), size=sample_count, replace=False)

fig, axes = plt.subplots(2, 4, figsize=(14, 7))
axes = axes.flatten()

for ax, idx in zip(axes, indices):
    ax.imshow(X_test[idx])
    true_label = idx_to_class[y_test[idx]]
    pred_label = idx_to_class[y_pred[idx]]

    title_color = "green" if true_label == pred_label else "red"
    ax.set_title(f"True: {true_label}\nPred: {pred_label}", color=title_color)
    ax.axis("off")

plt.tight_layout()
plt.savefig("sample_predictions/prediction_outputs.png", dpi=120, bbox_inches="tight")
plt.show()

### Brief interpretation
# The training and validation curves show how well the CNN learned from the image data.
# If both curves improve together, it means the model is learning properly.
# If training accuracy becomes much higher than validation accuracy, that would suggest overfitting.

# The confusion matrix helps show which classes are being predicted correctly and where
# the model gets confused. Since this is a 4-class problem, it is useful to inspect
# individual class performance rather than only looking at overall accuracy.

## Task 7: Business Use Case Mapping

# This type of CNN-based image classification system can be used in **manufacturing quality inspection**.

# In a factory setup, products can be photographed using cameras as they move through
# a production line. A trained CNN model can automatically inspect the product surface
# and classify it as:

# - normal
# - scratch
# - dent
# - stain

# This helps companies:
# - reduce manual inspection effort
# - improve consistency in quality checks
# - detect faulty products faster
# - reduce waste and rework
# - improve customer satisfaction

# So this kind of solution has a very practical use in automated defect detection.

















